services:
  db:
    image: postgres:17-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=mud-server-java
      - POSTGRES_PASSWORD=mud-server-java
      - POSTGRES_DB=mud-server-java
    volumes:
      - ./docker/build/db/postgres:/var/lib/postgresql/data
