spring:
  application:
    name: mud-server-java
  datasource:
    url: jdbc:postgresql://localhost:5433/mud-server-java
    username: mud-server-java
    password: mud-server-java
  flyway:
    locations: classpath:db/migration

app:
  telnet:
    port: 4001
